# Generated by Django 4.0.5 on 2023-02-04 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact_userprof_following_contact_user_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Re_quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='userprof',
            name='my_blocks',
            field=models.ManyToManyField(related_name='blocked_me', through='account.Blocking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprof',
            name='my_requests',
            field=models.ManyToManyField(related_name='requests', through='account.Re_quest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='re_quest',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='re_quest',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blocking',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blocking',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
