# Generated by Django 4.0.5 on 2023-02-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_blocking_re_quest_userprof_my_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprof',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
