# Generated by Django 4.0.5 on 2023-02-09 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprof_prof_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='userprof',
            name='my_directs',
            field=models.ManyToManyField(related_name='directs_me', through='account.Direct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direct',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direct',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
