# Generated by Django 4.0.5 on 2023-02-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_direct_userprof_my_directs_direct_user_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
