# Generated by Django 4.0.5 on 2023-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_direct_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='last_logedout',
            field=models.DateTimeField(null=True),
        ),
    ]
