# Generated by Django 4.0.5 on 2023-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprof_last_logedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprof',
            name='last_logedout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
