# Generated by Django 4.0.5 on 2023-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userprof_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprof',
            name='prof_image',
            field=models.ImageField(default='images/image_not_found.jpg', upload_to='static/images_prof'),
        ),
    ]
